Tout d'abord, modifiez le fichier vite.config.js pour ajouter le chemin de base pour GitHub Pages. Ce chemin doit être configuré en fonction du nom de votre dépôt.name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Changez "main" si votre branche par défaut a un autre nom

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
